### ISSUE TITLE
[BUG] - Plugin doesn't work on Better Discord

### ISSUE THREAD

**Issue by PixelGuy123** [An00nymushun/DiscordFreeEmojis#63]
***In case you don't know where the bug is in the code or what exactly causes it.***

**Describe the bug**
Simply doesn't work, if you open logs, after it starts, this error message appears:
`emojiPickerModule not found.`

**To Reproduce**
Install it on BD, then realize it doesn't work lol

Run it, lmao

`Make sure you can reproduce this problem yourself with your steps after restarting Discord!`

**Expected behavior**
Work _as expected_

**Screenshots**
![image](https://user-images.githubusercontent.com/89644121/197050369-201d85f1-0a08-49e2-88df-a8bc4440aa8a.png)

**Client:**
 - Windows 10
 - Stable (Release)
 - v1.6
 - v1.8.2 (BD)

**Additional context**
Yep

(Looks like people really complained about 48px version not working, here's the [download](https://github.com/An00nymushun/DiscordFreeEmojis/files/9933289/48Split.zip) link to a working one)
(Credits: SylveonBottle)

**Comment by Cerxi** [comment]
Strongly recommend you try updating to 1.7, the version that came out a month ago to fix this error.

**Comment by PixelGuy123** [comment]
Oh yeah I see now on the github, just a reminder: PLEASE update the plugin on the better discord website, so I don't have to do this manually

**Comment by SeasonalFerret** [comment]
[DiscordFreeEmojisSplit48px.plugin.js](https://github.com/An00nymushun/DiscordFreeEmojis/blob/master/DiscordFreeEmojisSplit48px.plugin.js) has yet to be updated.
Could this be re-opened?

**Comment by PixelGuy123** [comment]
K

**Comment by killshotroxs** [comment]
It still doesn't work for me in Better Discord.

**Comment by Ryuktheshinigamix** [comment]
same

**Comment by GokuUchihaDLuffy** [comment]
it still doesn't work on better discord

**Comment by PixelGuy123** [comment]
Just a reminder: 64px works fine on BD, you guys should try that instead (Idk the difference)

**Comment by SENPAY98K** [comment]
it still doesn't work on better discord

**Comment by SeasonalFerret** [comment]
I got DiscordFreeEmojisSplit48px working for me.
I just copied the changes that were made in the other versions over to Split48x.
I also just copied the code from #59 into it, and that worked perfectly as well.

**Comment by SENPAY98K** [comment]
> I got DiscordFreeEmojisSplit48px working for me. I just copied the changes that were made in the other versions over to Split48x. I also just copied the code from #59 into it, and that worked perfectly as well.

How to do that ?

**Comment by SeasonalFerret** [comment]
> How to do that ?

Use your problem-solving skills.

**Comment by SeasonalFerret** [comment]
Guys I literally just said "I just copied the changes that were made in the other versions over to Split48x." 
If that's too much for your 'problem solving skills' then you SERIOUSLY need to stop modding discord since you can't even figure out the simpliest of things.


Let's take this step by step.
First of all, [DiscordFreeEmojis64px.plugin.js](https://github.com/An00nymushun/DiscordFreeEmojis/blob/master/DiscordFreeEmojis64px.plugin.js) works perfectly fine but [DiscordFreeEmojisSplit48px.plugin.js](https://github.com/An00nymushun/DiscordFreeEmojis/blob/master/DiscordFreeEmojisSplit48px.plugin.js) doesn't work at all.
Why is that?

Well, according to the [commits](https://github.com/An00nymushun/DiscordFreeEmojis/commits/master) page, it shows that DiscordFreeEmojis64px.plugin.js was updated on [Sep 27](https://github.com/An00nymushun/DiscordFreeEmojis/commit/3c5f836d9abf1cd39190275d94e46dd620951c8a).

This looks like a very serious change. Lots of base classes were changed, and the major version number was increased from 1.6 to 1.7. 

Let's test it. Put DiscordFreeEmojis64px.plugin.js in your plugins folder, activate it, and.. it works!!
So, why does DiscordFreeEmojis**64**px.plugin.js work but DiscordFreeEmojis**Split48**px.plugin.js not work? It's because the author added these changes of the code to one, but seemingly forgot to add it to the other! 

So, let's add it to the other ourselves.

Following [this change log provided by github commits](https://github.com/An00nymushun/DiscordFreeEmojis/commit/3c5f836d9abf1cd39190275d94e46dd620951c8a), we have to:

- Replace `var useEmojiSelectHandlerHook;` with `var getEmojiUnavailableReasonHook;` on line 91
- Replace `const { original_parse, original_useEmojiSelectHandler } = Discord;` with `const { original_parse, original_getEmojiUnavailableReason } = Discord;` somewhere near the end
- Replace a few more things here and there (seriously read it)

Do you see the process? 
The author added code to the 64x plugin, but _forgot_ to add the exact same change to the 48xSplit version of the plugin. So we just need to add it ourselves!

Follow all of the code changes (literally just copy/paste the new code in) as shown by the change log [this change log provided by github commits](https://github.com/An00nymushun/DiscordFreeEmojis/commit/3c5f836d9abf1cd39190275d94e46dd620951c8a), and walla! We now have a fully functioning plugin.

**Comment by SeasonalFerret** [comment]
But wait, there's more! If you look over at the [Pull Requests](https://github.com/An00nymushun/DiscordFreeEmojis/pulls) of this project, you'll see a very awesome PR that someone has requested to add to the project that forces this plugin to use .png for better quality.
Well, how do we add this to our version?
Simple! Look at what the PR changes. [Here](https://github.com/An00nymushun/DiscordFreeEmojis/pull/59/commits/bb8a08029149ba19f23ab729da19c035689e67fc) and [here](https://github.com/An00nymushun/DiscordFreeEmojis/pull/59/commits/bbfb4ee7883237dc0d709d3ba24381ecb2a7fe5b).. and let's just copy/paste the exact same changes!


AWESOME! Now we have a fully functioning DiscordFreeEmojisSplit48px.plugin.js, AND it shows in better quality. Was that too hard?

It'd be awesome if the author of this project (An00nymushun) updated the plugin himself but until then we simply have to do it ourselves. It's not hard, it just requires using your brain.

**Comment by PixelGuy123** [comment]
Nice tutorial, now just use _problem-solving skills_

**Comment by SENPAY98K** [comment]
> 

We are not modding anything, we are just using it and are thankful to author and the helpers 😄

**Comment by SeasonalFerret** [comment]
For people too lazy to do it themselves, here's my compiled version of 48xSplit if you're willing to run code you randomly find off the internet (you shouldn't do this)
[48Split.zip](https://github.com/An00nymushun/DiscordFreeEmojis/files/9933289/48Split.zip)

Plugin is in the .zip folder, extract it to your betterdiscord plugin folder.

**Comment by SENPAY98K** [comment]
@SylveonBottle , it worked like magic, thanks a lot 😄❤️

**Comment by cheatachu72** [comment]
appreciate the prank SylveonBottle!! gave me a good laugh [-: for everyone else who isn't code-savvy enough to fix it themselves, here you go! 96% less jumpscares! guaranteed!

[FreemojiBUTAWESOME.zip](https://github.com/An00nymushun/DiscordFreeEmojis/files/10006081/FreemojiBUTAWESOME.zip)

**Comment by imthedoctorlol** [comment]
> appreciate the prank SylveonBottle!! gave me a good laugh [-: for everyone else who isn't code-savvy enough to fix it themselves, here you go! 96% less jumpscares! guaranteed!
> 
> [FreemojiBUTAWESOME.zip](https://github.com/An00nymushun/DiscordFreeEmojis/files/10006081/FreemojiBUTAWESOME.zip)

this better not pull a jumpscare randomly lmao

**Comment by killshotroxs** [comment]
> > appreciate the prank SylveonBottle!! gave me a good laugh [-: for everyone else who isn't code-savvy enough to fix it themselves, here you go! 96% less jumpscares! guaranteed!
> > [FreemojiBUTAWESOME.zip](https://github.com/An00nymushun/DiscordFreeEmojis/files/10006081/FreemojiBUTAWESOME.zip)
> 
> this better not pull a jumpscare randomly lmao

You really helped me thank you so much.

**Comment by SeasonalFerret** [comment]
> appreciate the prank SylveonBottle!! gave me a good laugh [-:

I could've changed the code to spam the API and get the user's account banned, or download a rat to give me access to their system.
But hopefully a small scare and a furry butt is a big enough price to pay for a good lesson about downloading random code off the internet without looking at it first.
Trust me, there were much harder ways to learn this lesson. The code on github is open-source _for a reason_. Look though it before you run it. Even if you don't know what you're reading, at the bare minimum you'll learn a little about the coding language and improve your skills and understanding..

**Comment by SENPAY98K** [comment]
> > appreciate the prank SylveonBottle!! gave me a good laugh [-:
> 
> I could've changed the code to spam the API and get the user's account banned, or download a rat to give me access to their system. But hopefully a small scare and a furry butt is a big enough price to pay for a good lesson about downloading random code off the internet without looking at it first. Trust me, there were much harder ways to learn this lesson. The code on github is open-source _for a reason_. Look though it before you run it. Even if you don't know what you're reading, at the bare minimum you'll learn a little about the coding language and improve your skills and understanding..

Good to know, only in github i dont pay much attention to files
